export const GET_IMAGE_FROM_QUERY_REQUEST = "GET_IMAGE_FROM_QUERY_REQUEST";
export const GET_IMAGE_FROM_QUERY_SUCCESS = "GET_IMAGE_FROM_QUERY_SUCCESS";
export const GET_IMAGE_FROM_QUERY_ERROR = "GET_IMAGE_FROM_QUERY_ERROR";
